require('plugins/which-key')
require('plugins/treesitter')
require('plugins/lualine')
require('plugins/telescope')
require('plugins/nvim-tree')
require('plugins/lspconfig')
require('plugins/vim-test')
require('plugins/close-buffers')
