theme = "darcula"

[editor]
true-color = true
color-modes = true
cursorline = true


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.statusline]
left = ["mode", "spinner", "diagnostics"]
center = ["file-name"]