format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$shell\
$python\
$character
"""

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = '\([$branch]($style) '

[git_status]
style = "cyan"
ahead = " [ 󰁝 ](green)"
behind = " [ 󰁅 ](red)"
conflicted = "[ $count](red)"
deleted = '[ ](yellow)'
diverged = '[ ](red)'
format = '$conflicted$untracked$modified$renamed$deleted$staged$ahead_behind$stashed\)'
modified = '[ ](yellow)'
renamed = "[ ](green)"
staged = '[ ](green)'
stashed = '[  $count](blue)'
untracked = '[ ](yellow)'
up_to_date = "  "


[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[shell]
disabled = false
bash_indicator = ""
zsh_indicator = ""
fish_indicator = "󰻴 "
powershell_indicator = " "
format = "[$indicator]($style) "
